steps:
  #install project dependancies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    #install firebase tools for deployment to firebase
    args: ['install', 'firebase-tools']
  #run the gatsby build process - setup env varaibles (these only used at build time so stored on trigger)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      [
        'CONTENTFUL_ID=${_CONTENTFUL_ID}',
        'CONTENTFUL_ACCESS_TOKEN=${_CONTENTFUL_ACCESS_TOKEN}',
      ]
  #deploy the resulting public directory to firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project', '$PROJECT_ID', '--token', '$_FIREBASE_TOKEN']
